### ISSUE TITLE
Azure Cosmos DB .NET SDK Version 3.0

### ISSUE THREAD

**Issue by Jeremywhiteley** [ealsur/serverless-recipes#1]
Any chance you will be doing a sample of the Cosmos DB static Client with the new Azure Cosmos DB .NET SDK Version 3.0?   https://azure.microsoft.com/en-us/blog/azure-cosmos-dotnet-sdk-version-3-0-now-in-public-preview/

**Comment by ealsur** [comment]
Done https://github.com/ealsur/serverless-recipes/blob/master/cosmosdbstaticclient/README.md
